spring:
  cloud:
    stream:
      kafka:
        binder:
          consumerProperties:
            auto:
              offset:
                reset: "latest"

  # Spring data rest
  data:
    rest:
      # Definition of page size for PagingAndSortingRepository
      max-page-size: 0x7fffffff
      default-page-size: 0x7fffffff
      return-body-on-update: true
      return-body-on-create: true

  datasource:
    url: jdbc:h2:file:~/repodb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
  # Spring JPA
  h2.console.enabled: true
  jpa:
    database: H2
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # Logging for database operation
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

# Define the keycloak development realm here
realm: ${SSO_REALM}
keycloak.auth-server-url: ${SSO_BASE_URL}

security:
  # possible values: none, all, changing (With changing, only changing requests such as POST, PUT, DELETE are logged)
  logging.requests: all
  oauth2:
    resource:
      prefer-token-info: false
    client:
      client-id: bpm-server
server:
  port: 8092

# kafka topics
digiwf:
  streaming:
    cocreationDeploy:
      topic: dwf-cocreation-deploy-local-01
    cocreationDeployDLQ:
      topic: dwf-cocreation-deploy-dlc-local-01
    group: "dwf-local-01"
  deployment:
    targets: "LOCAL, DEV, TEST, DEMO, PROCESSESTEST, PROCESSESDEMO, PROCESSESHOTFIX"
